apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: eagleeye007/profileservice  # it's a mix up while uploading the image i named frontend as profileserivce there is no issue here
        ports:
        - containerPort: 3000
